name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  rust-tests:
    name: Rust Tests
    runs-on: ubuntu-latest
    
    env:
      RUST_BACKTRACE: 1
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          
          # Search for available webkit packages
          echo "Searching for available webkit packages:"
          apt-cache search webkit2gtk | grep -E "dev|webkit2gtk"
          
          echo "Searching for available soup packages:"
          apt-cache search libsoup | grep -E "dev|libsoup"
          
          echo "Searching for available glib packages:"
          apt-cache search libglib | grep -E "dev|glib"
          
          # Install base packages that should always be available
          sudo apt-get install -y \
            pkg-config \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libudev-dev \
            libsqlite3-dev \
            libgtk-3-dev \
            libappindicator3-dev \
            librsvg2-dev \
            libglib2.0-dev \
            libcairo2-dev \
            libpango1.0-dev \
            libatk1.0-dev \
            libgdk-pixbuf-2.0-dev
          
          # Try webkit packages in order of preference
          if sudo apt-get install -y libwebkit2gtk-4.1-dev; then
            echo "✓ Installed libwebkit2gtk-4.1-dev"
          elif sudo apt-get install -y libwebkit2gtk-4.0-dev; then
            echo "✓ Installed libwebkit2gtk-4.0-dev"
          else
            echo "✗ Could not install webkit2gtk development packages"
          fi
          
          # Try soup packages in order of preference
          if sudo apt-get install -y libsoup-3.0-dev; then
            echo "✓ Installed libsoup-3.0-dev"
          elif sudo apt-get install -y libsoup2.4-dev; then
            echo "✓ Installed libsoup2.4-dev"
          else
            echo "✗ Could not install soup development packages"
          fi
          
          # Verify pkg-config can find the libraries
          echo "Checking pkg-config libraries:"
          pkg-config --exists glib-2.0 && echo "✓ glib-2.0 found" || echo "✗ glib-2.0 missing"
          pkg-config --exists gobject-2.0 && echo "✓ gobject-2.0 found" || echo "✗ gobject-2.0 missing"
          pkg-config --exists gtk+-3.0 && echo "✓ gtk+-3.0 found" || echo "✗ gtk+-3.0 missing"
          
          # Set PKG_CONFIG_PATH
          export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH"
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
      
      - name: Run Rust tests
        working-directory: src-tauri
        run: |
          # First try running tests normally
          cargo test --verbose || {
            echo "Regular tests failed, trying with minimal features..."
            cargo test --verbose --no-default-features || {
              echo "Tests failed with no default features. Checking environment..."
              echo "Rust version: $(rustc --version)"
              echo "Cargo version: $(cargo --version)"
              pkg-config --modversion glib-2.0 || echo "glib-2.0 not found"
              pkg-config --modversion gobject-2.0 || echo "gobject-2.0 not found"
              echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
              echo "Available .pc files:"
              find /usr -name "*.pc" 2>/dev/null | grep -E "(glib|gobject)" | head -10 || true
              exit 1
            }
          }

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    env:
      NODE_ENV: test
      CI: true
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies with retry
        run: |
          # Clear any existing installations
          rm -rf node_modules package-lock.json
          
          # Clean npm cache
          npm cache clean --force
          
          # Install dependencies with retries for robustness
          for i in {1..3}; do
            echo "Installation attempt $i"
            if npm install; then
              echo "Installation successful"
              break
            else
              echo "Installation failed, retrying..."
              rm -rf node_modules package-lock.json
              sleep 5
            fi
          done
          
          # Specifically install rollup native binary if missing
          if ! npm list @rollup/rollup-linux-x64-gnu >/dev/null 2>&1; then
            echo "Installing missing rollup native binary"
            npm install @rollup/rollup-linux-x64-gnu --save-optional || true
          fi
      
      - name: Run frontend tests
        run: |
          # Try running tests normally first
          if npm run test; then
            echo "Tests completed successfully"
          else
            echo "Tests failed with normal approach, trying alternative..."
            # If tests fail, try with alternative approaches
            echo "Checking rollup installation..."
            npm list rollup || npm install rollup --force
            npm run test || {
              echo "Frontend tests failed. Checking environment..."
              echo "Node version: $(node --version)"
              echo "NPM version: $(npm --version)"
              echo "Platform: $(uname -a)"
              ls -la node_modules/.bin/ | grep -E "(vitest|rollup)" || true
              echo "Package contents:"
              npm list --depth=0 | grep -E "(vitest|rollup)" || true
              exit 1
            }
          fi
